name: Deploy Portfolio Website

on:
  push:
    branches:
      - main  # Ensure this matches the branch you're working on.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # The branch for GitHub Pages deployment.
        publish_dir: Portfolio-paradigm-shift  # Folder containing your portfolio files.
