name: Deploy Portfolio Website

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure Portfolio Directory Exists
      run: |
        if [ ! -d "Portfolio" ]; then
          echo "Error: Portfolio folder is missing!"
          exit 1
        fi

    - name: Build or Prepare Site (if needed)
      run: echo "Site is ready for deployment"

    - name: Verify Deployment Files
      run: ls -l Portfolio
